export const LIVE_GAMES = [
  {
    id: "chat",
    emoji: "💬",
    name: "Chat Room",
    tagline: "Talk. No signup. Ever.",
    desc: "Spin up a private room in seconds. Share the code, end-to-end encrypted.",
    players: "12k",
    bg: "linear-gradient(140deg,#4c1d95 0%,#7c3aed 60%,#6d28d9 100%)",
    accent: "#a855f7",
    accentLight: "#d8b4fe",
    glow: "rgba(168,85,247,.55)",
    glowLight: "rgba(168,85,247,.22)",
    path: "/chat",
  },
  {
    id: "bingo",
    emoji: "🎱",
    name: "Bingo Battle",
    tagline: "First to BINGO wins.",
    desc: "Head-to-head real-time bingo against a friend. Number calls, strategy, bragging rights.",
    players: "8k",
    bg: "linear-gradient(140deg,#164e63 0%,#0e7490 60%,#0c4a6e 100%)",
    accent: "#06b6d4",
    accentLight: "#a5f3fc",
    glow: "rgba(6,182,212,.5)",
    glowLight: "rgba(6,182,212,.22)",
    path: "/bingo",
  },
  {
    id: "dots",
    emoji: "🔲",
    name: "Dots & Boxes",
    tagline: "Claim boxes. Outsmart everyone.",
    desc: "Draw lines, complete boxes, dominate the board. A timeless strategy duel.",
    players: "6k",
    bg: "linear-gradient(140deg,#78350f 0%,#b45309 60%,#92400e 100%)",
    accent: "#f59e0b",
    accentLight: "#fde68a",
    glow: "rgba(245,158,11,.5)",
    glowLight: "rgba(245,158,11,.22)",
    path: "/dotsboxes",
  },
];

export const SOON_GAMES = [
  { emoji: "♟️", name: "Chess", sub: "Classic. Timeless." },
  { emoji: "🟩", name: "Word Duel", sub: "Race to guess it." },
  { emoji: "🃏", name: "Card Clash", sub: "No mercy. Just cards." },
  { emoji: "🎯", name: "Bullseye", sub: "Aim. Fire. Win." },
];